#!/usr/bin/env python

import random, sys, os

random.seed()
nonword = "\n"
w1 = nonword
w2 = nonword

table = {}

args = ''
if len(sys.argv) > 1:
    args = ' '.join(sys.argv[1::])

git_log = os.popen("git log " + args)
for line in git_log:
    words = line.split()
    if len(words) and words[0] not in ('commmit', 'Author:', 'Date:'):
        for word in words:
            table.setdefault( (w1, w2), [] ).append(word)
            w1, w2 = w2, word

table.setdefault( (w1, w2), [] ).append(nonword)

maxwords = int(random.random() * 50) + 10
(w1, w2) = random.choice(table.keys())

first = True
for i in xrange(maxwords):
    newword = random.choice(table[(w1, w2)])
    if newword == nonword: sys.exit()
    if first:
        print(newword.capitalize()),
        first = False
    else:
        print(newword),
    w1, w2 = w2, newword

print random.choice(("Ha", "Haha", "Waka waka!", "Heyoooo!", "Ba-dum Ting!"))
